import { calculatePriority, type PriorityLevel } from "../services/priority-engine";
export type DashboardIncident = { id:string; disasterType:"flood"; title:string; description:string; latitude:number; longitude:number; severity:number; confidence:number; peopleAffected:number; source:string; timestamp:string; accessibility:number; status:"awaiting_response"|"in_progress"|"resolved"; priorityScore:number; priorityLevel:PriorityLevel; incidentType:string; aiSummary:string; isDemo:boolean; };
const now=Date.now();
const demo=(id:string,title:string,description:string,lat:number,lon:number,severity:number,people:number,accessibility:number,source:string,type:string,age:number):DashboardIncident=>{ const confidence=source==="Emergency Services"?0.96:source==="Field Officer"?0.91:0.78; const priority=calculatePriority({severity,peopleAffected:people,immediateThreat:Math.min(10,severity+(people>20?1:0)),accessibility,timeCriticality:Math.max(1,10-age/18)}); return {id,title,description,latitude:lat,longitude:lon,severity,confidence,peopleAffected:people,source,timestamp:new Date(now-age*60000).toISOString(),accessibility,status:priority.level==="critical"?"awaiting_response":"in_progress",priorityScore:priority.score,priorityLevel:priority.level,disasterType:"flood",incidentType:type,aiSummary:description,isDemo:true}; };
export const DEMO_INCIDENTS:DashboardIncident[]=[
demo("demo-1","Families trapped at Sector 4 apartments","Six residents, including an elderly person, are trapped above rising floodwater. Main access is blocked.",28.6139,77.2090,9,32,2,"Emergency Services","Rescue required",12),
demo("demo-2","Medical emergency at Yamuna camp","Field team reports a diabetic patient and two children needing urgent evacuation from a low-lying relief camp.",28.6208,77.2410,8,18,3,"Field Officer","Medical emergency",28),
demo("demo-3","Bridge approach washed out","Water has overtopped the eastern approach. Rescue vehicles cannot pass; alternate route remains open via Ring Road.",28.6015,77.2520,8,0,1,"Satellite","Blocked road",44),
demo("demo-4","School shelter nearing capacity","Temporary shelter is operational with 74 displaced residents and limited drinking water.",28.6295,77.2170,6,74,7,"Citizen","Shelter capacity",62),
demo("demo-5","Roof collapse near Nizamuddin","Partial building collapse reported after prolonged waterlogging; occupancy is unconfirmed.",28.5892,77.2505,7,12,4,"Drone","Damaged building",36),
demo("demo-6","Stranded commuters on underpass","A bus is stalled in knee-deep water. Eight commuters are waiting for assistance.",28.5750,77.2300,6,8,4,"Citizen","People stranded",75),
demo("demo-7","Hospital access route flooded","Ambulance access is restricted on the southern lane; hospital remains operational.",28.5672,77.2431,5,0,3,"Emergency Services","Hospital access",91),
demo("demo-8","Power substation water ingress","Sensor alert indicates rising water near a live substation. Isolation requested as a precaution.",28.6401,77.1905,5,0,5,"Sensor","Infrastructure risk",115),
demo("demo-9","Open road reported at Lodhi Road","Field officer confirms the northern evacuation corridor is currently passable.",28.5921,77.2268,2,0,9,"Field Officer","Safe corridor",135),
demo("demo-10","Isolated household requests supplies","Single household reports food shortage but no immediate medical threat.",28.6338,77.2600,3,4,6,"Social Media","Supply request",150)];
export function buildDashboard(incidents:DashboardIncident[]){ const active=incidents.filter(i=>i.status!=="resolved"); const critical=active.filter(i=>i.priorityLevel==="critical"); const affected=active.reduce((s,i)=>s+i.peopleAffected,0); const top=[...active].sort((a,b)=>b.priorityScore-a.priorityScore)[0]; const blocked=active.filter(i=>i.incidentType.toLowerCase().includes("road")||i.incidentType.toLowerCase().includes("access")); const summary=top?"Severe flooding is concentrated around "+top.title+". "+affected+" people are represented across "+active.length+" active incidents. "+blocked.length+" access constraints are affecting response routes. "+top.title+" is the highest-priority zone with a "+top.priorityScore+"/10 score and "+Math.round(top.confidence*100)+"% confidence.":"No active incidents are currently reported."; const recommendations=critical.slice(0,3).map((i,index)=>({id:"rec-"+i.id,priority:index===0?"critical":"high",action:i.incidentType.includes("Medical")?"Dispatch a medical unit":i.incidentType.includes("road")||i.incidentType.includes("access")?"Clear and secure the access route":"Deploy a rescue team",reason:"Priority score "+i.priorityScore+"/10; "+i.peopleAffected+" people affected; confidence "+Math.round(i.confidence*100)+"%.",targetLocation:i.title,requiredResource:i.incidentType.includes("Medical")?"Medical response team":"Water rescue team",status:"pending"})); return {incidents,stats:{activeIncidents:active.length,criticalIncidents:critical.length,affectedPopulation:affected,activeOperations:active.filter(i=>i.status==="in_progress").length,incomingReports:incidents.length},summary,recommendations,generatedAt:new Date().toISOString(),isDemo:incidents.every(i=>i.isDemo)}; }